name: PlateStack
version: 0.1.0-SNAPSHOT
description: PlateStack server implementation for CraftBukkit servers

author: joserobjr
website: http://platestack.org

main: org.platestack.bukkit.server.PlateStackLoader

